import { START_FEN, initialTheme } from "./config.js";
import { loadBlobMemory } from "./memory.js";

const refs = {
  introScreen: document.querySelector("#introScreen"),
  introCoreTrigger: document.querySelector("#introCoreTrigger"),
  introCore: document.querySelector("#introCore"),
  introState: document.querySelector("#introState"),
  introCopy: document.querySelector(".intro-copy"),
  wakeSgurrButton: document.querySelector("#wakeSgurrButton"),
  menuScreen: document.querySelector("#menuScreen"),
  menuCore: document.querySelector("#menuCore"),
  menuStatus: document.querySelector("#menuStatus"),
  menuMemory: document.querySelector("#menuMemory"),
  menuTimeButton: document.querySelector("#menuTimeButton"),
  menuEngineButton: document.querySelector("#menuEngineButton"),
  menuThemeButton: document.querySelector("#menuThemeButton"),
  timeDownButton: document.querySelector("#timeDownButton"),
  timeUpButton: document.querySelector("#timeUpButton"),
  engineDownButton: document.querySelector("#engineDownButton"),
  engineUpButton: document.querySelector("#engineUpButton"),
  coreEngineName: document.querySelector("#coreEngineName"),
  coreEngineSubtitle: document.querySelector("#coreEngineSubtitle"),
  themeDownButton: document.querySelector("#themeDownButton"),
  themeUpButton: document.querySelector("#themeUpButton"),
  playWhiteButton: document.querySelector("#playWhiteButton"),
  playBlackButton: document.querySelector("#playBlackButton"),
  watchButton: document.querySelector("#watchButton"),
  positionLabButton: document.querySelector("#positionLabButton"),
  menuSettingsButton: document.querySelector("#menuSettingsButton"),
  menuHelpButton: document.querySelector("#menuHelpButton"),
  appShell: document.querySelector("#appShell"),
  focusModeButton: document.querySelector("#focusModeButton"),
  sidePanel: document.querySelector(".side-panel"),
  editorPanel: document.querySelector("#editorPanel"),
  analysisPanel: document.querySelector("#analysisPanel"),
  board: document.querySelector("#board"),
  boardWrap: document.querySelector(".board-wrap"),
  mateDevour: document.querySelector("#mateDevour"),
  mateDevourPiece: document.querySelector("#mateDevourPiece"),
  topPlayerCard: document.querySelector("#topPlayerCard"),
  topPlayerPresence: document.querySelector("#topPlayerPresence"),
  topPlayerName: document.querySelector("#topPlayerName"),
  topPlayerClock: document.querySelector("#topPlayerClock"),
  bottomPlayerCard: document.querySelector("#bottomPlayerCard"),
  bottomPlayerPresence: document.querySelector("#bottomPlayerPresence"),
  bottomPlayerName: document.querySelector("#bottomPlayerName"),
  bottomPlayerClock: document.querySelector("#bottomPlayerClock"),
  statusPill: document.querySelector("#statusPill"),
  movetimeSelect: document.querySelector("#movetimeSelect"),
  newGameButton: document.querySelector("#newGameButton"),
  mainMenuButton: document.querySelector("#mainMenuButton"),
  pauseWatchButton: document.querySelector("#pauseWatchButton"),
  undoMoveButton: document.querySelector("#undoMoveButton"),
  redoMoveButton: document.querySelector("#redoMoveButton"),
  engineNowButton: document.querySelector("#engineNowButton"),
  copyFenButton: document.querySelector("#copyFenButton"),
  exportPgnButton: document.querySelector("#exportPgnButton"),
  sideSettingsButton: document.querySelector("#sideSettingsButton"),
  sideHelpButton: document.querySelector("#sideHelpButton"),
  sideTimeControl: document.querySelector("#sideTimeControl"),
  watchTimeControl: document.querySelector("#watchTimeControl"),
  watchWhiteInstance: document.querySelector("#watchWhiteInstance"),
  watchBlackInstance: document.querySelector("#watchBlackInstance"),
  watchWhiteCore: document.querySelector("#watchWhiteCore"),
  watchBlackCore: document.querySelector("#watchBlackCore"),
  watchWhiteClock: document.querySelector("#watchWhiteClock"),
  watchBlackClock: document.querySelector("#watchBlackClock"),
  watchMatchLine: document.querySelector("#watchMatchLine"),
  turnValue: document.querySelector("#turnValue"),
  resultValue: document.querySelector("#resultValue"),
  statusValue: document.querySelector("#statusValue"),
  evalChip: document.querySelector("#evalChip"),
  evalFill: document.querySelector("#evalFill"),
  evalValue: document.querySelector("#evalValue"),
  evalMeta: document.querySelector("#evalMeta"),
  materialValue: document.querySelector("#materialValue"),
  materialDiff: document.querySelector("#materialDiff"),
  capturedPieces: document.querySelector("#capturedPieces"),
  moveRows: document.querySelector("#moveRows"),
  movesScroll: document.querySelector("#movesScroll"),
  plyCount: document.querySelector("#plyCount"),
  trendValue: document.querySelector("#trendValue"),
  trendPath: document.querySelector("#trendPath"),
  trendDot: document.querySelector("#trendDot"),
  statusModeLabel: document.querySelector("#statusModeLabel"),
  backendValue: document.querySelector("#backendValue"),
  engineDot: document.querySelector("#engineDot"),
  coreLine: document.querySelector("#coreLine"),
  promotionBackdrop: document.querySelector("#promotionBackdrop"),
  promotionDialog: document.querySelector("#promotionDialog"),
  promotionChoices: document.querySelector("#promotionChoices"),
  themeModal: document.querySelector("#themeModal"),
  themeGallery: document.querySelector("#themeGallery"),
  reviewBlock: document.querySelector("#reviewBlock"),
  reviewMove: document.querySelector("#reviewMove"),
  reviewEval: document.querySelector("#reviewEval"),
  reviewScrub: document.querySelector("#reviewScrub"),
  reviewCounter: document.querySelector("#reviewCounter"),
  reviewStartButton: document.querySelector("#reviewStartButton"),
  reviewPrevButton: document.querySelector("#reviewPrevButton"),
  reviewNextButton: document.querySelector("#reviewNextButton"),
  reviewEndButton: document.querySelector("#reviewEndButton"),
  reviewExitButton: document.querySelector("#reviewExitButton"),
  reviewSwingButton: document.querySelector("#reviewSwingButton"),
  reviewGameButton: document.querySelector("#reviewGameButton"),
  trendLabel: document.querySelector("#trendLabel"),
  trendSwingMark: document.querySelector("#trendSwingMark"),
  engineModal: document.querySelector("#engineModal"),
  engineGallery: document.querySelector("#engineGallery"),
  menuEngineCaption: document.querySelector("#menuEngineCaption"),
  watchArenaTitle: document.querySelector("#watchArenaTitle"),
  timeModal: document.querySelector("#timeModal"),
  timeGallery: document.querySelector("#timeGallery"),
  settingsModal: document.querySelector("#settingsModal"),
  helpModal: document.querySelector("#helpModal"),
  autoFlipInput: document.querySelector("#autoFlipInput"),
  showEngineInfoInput: document.querySelector("#showEngineInfoInput"),
  animationModeSelect: document.querySelector("#animationModeSelect"),
  soundEnabledInput: document.querySelector("#soundEnabledInput"),
  soundVolumeInput: document.querySelector("#soundVolumeInput"),
  musicEnabledInput: document.querySelector("#musicEnabledInput"),
  musicVolumeInput: document.querySelector("#musicVolumeInput"),
  gameMusicEnabledInput: document.querySelector("#gameMusicEnabledInput"),
  gameMusicVolumeInput: document.querySelector("#gameMusicVolumeInput"),
  clearPreferencesButton: document.querySelector("#clearPreferencesButton"),
  clearMemoryButton: document.querySelector("#clearMemoryButton"),
  resultModal: document.querySelector("#resultModal"),
  resultSystemLabel: document.querySelector(".result-system-label"),
  resultKing: document.querySelector("#resultKing"),
  resultDualKings: document.querySelector("#resultDualKings"),
  resultWhiteKing: document.querySelector("#resultWhiteKing"),
  resultBlackKing: document.querySelector("#resultBlackKing"),
  resultTitle: document.querySelector("#resultTitle"),
  resultDetail: document.querySelector("#resultDetail"),
  resultPill: document.querySelector("#resultPill"),
  rematchButton: document.querySelector("#rematchButton"),
  resultMenuButton: document.querySelector("#resultMenuButton"),
  editorPlayerButton: document.querySelector("#editorPlayerButton"),
  editorTurnButton: document.querySelector("#editorTurnButton"),
  editorPlayButton: document.querySelector("#editorPlayButton"),
  editorAnalyseButton: document.querySelector("#editorAnalyseButton"),
  editorHeading: document.querySelector("#editorHeading"),
  editorPurpose: document.querySelector("#editorPurpose"),
  editorFenInput: document.querySelector("#editorFenInput"),
  editorLoadFenButton: document.querySelector("#editorLoadFenButton"),
  editorDrills: document.querySelector("#editorDrills"),
  editorOddsRecipientButton: document.querySelector("#editorOddsRecipientButton"),
  editorOdds: document.querySelector("#editorOdds"),
  editorStartButton: document.querySelector("#editorStartButton"),
  editorCopyFenButton: document.querySelector("#editorCopyFenButton"),
  editorClearButton: document.querySelector("#editorClearButton"),
  editorCancelButton: document.querySelector("#editorCancelButton"),
  editorMainMenuButton: document.querySelector("#editorMainMenuButton"),
  editorSettingsButton: document.querySelector("#editorSettingsButton"),
  editorHelpButton: document.querySelector("#editorHelpButton"),
  editorPalette: document.querySelector("#editorPalette"),
  editorStatus: document.querySelector("#editorStatus"),
  analysisEngineName: document.querySelector("#analysisEngineName"),
  analysisStatus: document.querySelector("#analysisStatus"),
  analysisCore: document.querySelector("#analysisCore"),
  analysisScore: document.querySelector("#analysisScore"),
  analysisBestMove: document.querySelector("#analysisBestMove"),
  analysisBestMoveUci: document.querySelector("#analysisBestMoveUci"),
  analysisDepth: document.querySelector("#analysisDepth"),
  analysisNodes: document.querySelector("#analysisNodes"),
  analysisNps: document.querySelector("#analysisNps"),
  analysisTime: document.querySelector("#analysisTime"),
  analysisLineLabel: document.querySelector("#analysisLineLabel"),
  analysisPlyCounter: document.querySelector("#analysisPlyCounter"),
  analysisPvMoves: document.querySelector("#analysisPvMoves"),
  analysisPrevPlyButton: document.querySelector("#analysisPrevPlyButton"),
  analysisRootButton: document.querySelector("#analysisRootButton"),
  analysisNextPlyButton: document.querySelector("#analysisNextPlyButton"),
  analysisDepths: document.querySelector("#analysisDepths"),
  analysisDecisionSummary: document.querySelector("#analysisDecisionSummary"),
  analysisChangeCount: document.querySelector("#analysisChangeCount"),
  analysisLiveBadge: document.querySelector("#analysisLiveBadge"),
  analysisStopButton: document.querySelector("#analysisStopButton"),
  analysisAgainButton: document.querySelector("#analysisAgainButton"),
  analysisEditButton: document.querySelector("#analysisEditButton"),
  analysisCopyFenButton: document.querySelector("#analysisCopyFenButton"),
  analysisMenuButton: document.querySelector("#analysisMenuButton"),
  analysisLimitNote: document.querySelector("#analysisLimitNote"),
};

const app = {
  fen: START_FEN,
  startFen: START_FEN,
  turn: "white",
  legalMoves: [],
  premoveMoves: [],
  basePremoveMoves: [],
  premoves: [],
  premoveRequestToken: 0,
  moves: [],
  moveRows: [],
  lastMove: null,
  latestEval: null,
  evalHistory: [],
  // Full per-ply record for post-game review. evalHistory above is capped for
  // the live sparkline and cannot describe a whole game; see js/review.js.
  review: { active: false, index: 0, plies: [] },
  material: null,
  canMate: { white: true, black: true },
  gameOver: false,
  result: null,
  winner: null,
  reason: null,
  inCheck: false,
  gameOverRevealAt: null,
  gameOverRevealTimer: null,
  mode: "menu",
  humanSide: "white",
  selected: null,
  busy: false,
  thinking: false,
  coreCooling: false,
  coreCoolingTimer: null,
  watchPaused: false,
  watchTimer: null,
  manualFlip: false,
  engineAutoPaused: false,
  clocks: { white: 0, black: 0 },
  clockLastTick: null,
  clockFlagged: null,
  clockCueSecond: null,
  searchToken: 0,
  coreMessage: "Opponent core online",
  coreLineMode: "system",
  coreDialogueLastPly: -99,
  coreDialogueLastKey: "",
  coreThinkingIndex: 0,
  coreThinkingTimer: null,
  coreLineFading: false,
  coreLineFadeTimer: null,
  history: [],
  redoStack: [],
  status: "Choose a side",
  error: "",
  backendOk: false,
  engineExists: false,
  publicDemo: false,
  backendDetail: "checking",
  menuMessage: "",
  pendingStartSide: undefined,
  themeKey: initialTheme,
  timeIndex: Number(localStorage.getItem("sgurrTimeIndex") || "2"),
  engines: [],
  selectedEngineIndex: 0,
  engineLabel: 'Sgurr v8.2 "Thearlaich"',
  engineSubtitle: "GEN8 NNUE + PACKED TT · ~3012",
  autoFlipAsBlack: localStorage.getItem("sgurrAutoFlip") !== "false",
  showEngineInfo: localStorage.getItem("sgurrShowEngineInfo") !== "false",
  animationMode: localStorage.getItem("sgurrAnimationMode") === "Off" ? "Off" : "On",
  soundEnabled: localStorage.getItem("sgurrSoundEnabled") !== "false",
  soundVolume: Number(localStorage.getItem("sgurrSoundVolume") || "0.8"),
  musicEnabled: localStorage.getItem("sgurrMusicEnabled") !== "false",
  musicVolume: Number(localStorage.getItem("sgurrMusicVolume") || "0.2"),
  gameMusicEnabled: localStorage.getItem("sgurrGameMusicEnabled") !== "false",
  gameMusicVolume: Number(localStorage.getItem("sgurrGameMusicVolume") || "0.35"),
  audioUnlocked: false,
  audio: {},
  audioContext: null,
  musicAudio: null,
  musicFadeFrame: null,
  musicFadeTarget: null,
  musicShouldRun: false,
  musicShouldPlay: false,
  gameMusicAudio: {},
  gameMusicFadeFrame: null,
  gameMusicMixKey: "",
  intro: {
    complete: false,
    waking: false,
    revealing: false,
    wakeTimer: null,
    nameTimer: null,
    blackoutTimer: null,
    handoffTimer: null,
    revealTimer: null,
    handoffAnimation: null,
  },
  focusMode: false,
  currentOpening: null,
  openingAnnouncedKey: "",
  openingAnnouncedDepth: 0,
  memory: loadBlobMemory(),
  memoryRecorded: false,
  drag: {
    active: false,
    pointerId: null,
    mode: null,
    from: null,
    piece: null,
    startX: 0,
    startY: 0,
    x: 0,
    y: 0,
    ghost: null,
    suppressClick: false,
  },
  pendingAnimation: null,
  activeAnimation: null,
  resultSoundPlayed: false,
  lastMoveInfo: null,
  editor: {
    previousMode: "menu",
    pieces: {},
    initialised: false,
    turn: "white",
    castlingRights: "KQkq",
    epSquare: "-",
    halfmoveClock: 0,
    fullmoveNumber: 1,
    returnSide: "white",
    oddsRecipient: "you",
    brush: null,
    heldPiece: null,
    heldFrom: null,
    status: "Position Lab ready",
    error: "",
  },
  analysis: {
    sourceFen: START_FEN,
    orientation: "white",
    iterations: [],
    selectedDepth: null,
    selectedPly: 0,
    running: false,
    complete: false,
    stopped: false,
    error: "",
    status: "Ready to analyse",
    engineLabel: 'Sgurr v8.2 "Thearlaich"',
    movetimeMs: 5_000,
    bestmove: null,
    bestmoveSan: null,
    controller: null,
    runId: 0,
  },
  gameOrigin: "standard",
};

if (!Number.isFinite(app.soundVolume)) {
  app.soundVolume = 0.8;
}
app.soundVolume = Math.max(0, Math.min(1, app.soundVolume));
if (!Number.isFinite(app.musicVolume)) {
  app.musicVolume = 0.2;
}
app.musicVolume = Math.max(0, Math.min(1, app.musicVolume));
if (!Number.isFinite(app.gameMusicVolume)) {
  app.gameMusicVolume = 0.35;
}
app.gameMusicVolume = Math.max(0, Math.min(1, app.gameMusicVolume));

export {
  refs,
  app,
};
